# Zsh configuration
export ZSH=$HOME/.dotfiles/oh-my-zsh
. $ZSH/oh-my-zsh.sh

DISABLE_UPDATE_PROMPT=true # auto update w/o prompting

# Antigen configuration
. ~/clones/antigen/antigen.zsh

antigen use oh-my-zsh

bundle=(
  command-not-found
  common-aliases
  cp
  docker
  git
  osx
  tmux
  tmuxinator
  zsh-users/zsh-syntax-highlighting
)

antigen bundle "${bundle[@]}"

antigen theme robbyrussell

antigen apply

# Path configuration
export WORKON_HOME=~/envs
export JAVA_HOME=$(/usr/libexec/java_home)
export PROJECT_HOME=$HOME/PycharmProjects/
export NVM_DIR="$HOME/.nvm"

# Execute script
. "$(brew --prefix nvm)/nvm.sh"

# Other configuration
PYTHONIOENCODING="UTF-8"
export XTERM=xterm-256color

export VISUAL=nvim
export EDITOR="$VISUAL"
export CVSEDITOR="$VISUAL"
export SVN_EDITOR="$VISUAL"
export GIT_EDITOR="$VISUAL"

bindkey -e
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word

# Aliases
[[ -f ~/.aliases ]] && source ~/.aliases

# Local config
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

